#' Iterate \code{equivTestSorensen} along the specified GO ontologies and GO
#' levels
#'
#' @param x either an object of class "list" or an object of class
#' "allTableList". In the first case, each of its elements must be a "character"
#' vector of gene identifiers (e.g., ENTREZ).
#' @param d0 equivalence threshold for the Sorensen-Dice dissimilarity, d.
#' The null hypothesis states that d >= d0, i.e., inequivalence between the
#' compared gene lists and the alternative that d < d0, i.e., equivalence or
#' dissimilarity irrelevance (up to a level d0).
#' @param conf.level confidence level of the one-sided confidence interval, a
#' value between 0 and 1.
#' @param boot boolean. If TRUE, the confidence interval and the test p-value
#' are computed by means of a bootstrap approach instead of the asymptotic
#' normal approach. Defaults to FALSE.
#' @param nboot numeric, number of initially planned bootstrap replicates.
#' Ignored if \code{boot == FALSE}. Defaults to 10000.
#' @param check.table Boolean. If TRUE (default), argument \code{x} is checked
#' to adequately represent a 2x2 contingency table (or an aggregate of them) or
#' gene lists producing a correct table. This checking is performed by means of
#' function \code{nice2x2Table}.
#' @param ontos "character", GO ontologies to analyse. Defaults to
#' \code{c("BP", "CC", "MF")}.
#' @param GOLevels Integer vector of GO levels to analyze inside each selected
#' ontology.
#'   If \code{NULL}, equivalence tests are performed without restricting the
#'   analysis to specific
#'   GO levels.
#' @param trace Logical. If TRUE (default), the (usually very time consuming)
#' process of function
#' \code{allEquivTestSorensen} is traced along the specified GO ontologies and
#' levels.
#' @param ... extra parameters for function \code{buildEnrichTable}.
#'
#' @return
#' An object of class "AllEquivSDhtest". It is a list with as many components as
#' GO ontologies have been analyzed.
#'
#' If \code{GOLevels} is not \code{NULL}, each ontology component is itself a
#' list with as many components as GO levels have been analyzed. Each of these
#' elements is an object generated by
#' \code{equivTestSorensen.list()} or \code{equivTestSorensen.tableList()}, that
#' is, an object of class "equivSDhtestList" containing pairwise comparisons
#' between gene lists.
#'
#' If \code{GOLevels = NULL}, each ontology component is directly an object of
#' class "equivSDhtestList", containing all pairwise equivalence tests between
#' the gene lists in argument \code{x}, without GO level restriction.
#'
#' @examples
#' ## The following example is highly time-consuming and is therefore not run
#' ## automatically during R CMD check.
#'
#' \dontrun{
#' ## i) Obtaining ENTREZ identifiers for the gene universe of humans:
#' library(org.Hs.eg.db)
#' humanEntrezIDs <- keys(org.Hs.eg.db, keytype = "ENTREZID")
#'
#' ## ii) Gene lists to be explored for analysis:
#' data(allOncoGeneLists)
#'
#' # iii) Calculation of equivalence tests for all joint enrichment contingency
#' # tables across GO levels 3 to 10 for the BP, CC, and MF ontologies
#' allEqTests <- allEquivTestSorensen(allOncoGeneLists,
#'   geneUniverse = humanEntrezIDs,
#'   orgPackg = "org.Hs.eg.db",
#'   ontos = c("BP", "CC", "MF"),
#'   GOLevels = 3:10,
#'   d0 = 0.4444,
#'   conf.level = 0.95
#' )
#' allEqTests
#' }
#'
#' # Since running this example may take several minutes, the result has been
#' # pre-computed and is accessible as the following:
#' data(allEqTests)
#' allEqTests
#' # This shortcut applies only to this example; for your own gene-list data,
#' # the computation must be performed explicitly.
#'
#' # For a complete overview of this function's use, see the section 4 of the
#' # vignette "Introduction to goSorensen". You can do this by consulting the
#' # general package documentation or by directly running the following code in
#' # the R console:
#' # vignette("goSorensen_Introduction", package = "goSorensen")
#'
#' @export
allEquivTestSorensen <- function(x, ...) {
  UseMethod("allEquivTestSorensen")
}

#' @describeIn allEquivTestSorensen S3 method for class "list"
#' @export
allEquivTestSorensen.list <- function(x, d0 = 1 / (1 + 1.25), conf.level = 0.95,
                                      boot = FALSE, nboot = 10000,
                                      check.table = TRUE,
                                      ontos = c("BP", "CC", "MF"),
                                      GOLevels = GOLevels,
                                      trace = TRUE,
                                      ...) {
  allOntos <- lapply(ontos, function(onto) {
    if (trace) {
      message("\nPerforming all equivalence tests for ontology", onto, "\n")
    }

    # Si NO se quiere tomar en cuenta el nivel
    if (is.null(GOLevels)) {
      result <- equivTestSorensen(
        x,
        d0 = d0,
        conf.level = conf.level,
        boot = boot,
        nboot = nboot,
        check.table = check.table,
        onto = onto,
        ...
      )
      return(result)
    }

    # Si sí se quieren niveles específicos
    thisOnto <- lapply(GOLevels, function(lev) {
      if (trace) {
        message("\n Level ", lev, "\n")
      }

      result <- equivTestSorensen(
        x,
        d0 = d0,
        conf.level = conf.level,
        boot = boot,
        nboot = nboot,
        check.table = check.table,
        onto = onto,
        GOLevel = lev,
        ...
      )
      return(result)
    })

    names(thisOnto) <- paste("level", GOLevels)
    return(thisOnto)
  })

  names(allOntos) <- ontos
  class(allOntos) <- c("AllEquivSDhtest", "list")
  return(allOntos)
}

#' @describeIn allEquivTestSorensen S3 method for class "allTableList"
#' @export
allEquivTestSorensen.allTableList <- function(x, d0 = 1 / (1 + 1.25),
                                              conf.level = 0.95,
                                              boot = FALSE, nboot = 10000,
                                              check.table = TRUE,
                                              ontos, GOLevels, trace = TRUE,
                                              ...) {
  if (missing(ontos)) {
    ontos <- names(x)
  }

  missGOLevels <- missing(GOLevels)
  if (missGOLevels) {
    GOLevels <- attr(x, "GOLevels")
  }

  allOntos <- lapply(ontos, function(ontoName) {
    onto <- x[[ontoName]]

    if (is.null(onto)) {
      return(NULL)
    }

    if (trace) {
      message("\nPerforming all equivalence tests for ontology", ontoName, "\n")
    }

    # Caso 1: GOLevels = NULL
    if (is.null(GOLevels)) {
      result <- equivTestSorensen(
        onto,
        d0 = d0,
        conf.level = conf.level,
        boot = boot,
        nboot = nboot,
        check.table = check.table,
        ...
      )
      return(result)
    }

    # Caso 2: niveles específicos
    levNames <- paste("level", GOLevels)

    thisOnto <- lapply(levNames, function(levName) {
      GOlevel <- onto[[levName]]

      if (is.null(GOlevel)) {
        return(NULL)
      }

      if (trace) {
        message("\n", levName, "\n")
      }

      result <- equivTestSorensen(
        GOlevel,
        d0 = d0,
        conf.level = conf.level,
        boot = boot,
        nboot = nboot,
        check.table = check.table,
        ...
      )
      return(result)
    })

    names(thisOnto) <- levNames
    return(thisOnto)
  })

  names(allOntos) <- ontos
  class(allOntos) <- c("AllEquivSDhtest", "list")
  return(allOntos)
}
