#' 14 gene lists possibly related with kidney transplant rejection
#'
#' An object of class "list" of length 14. A non up-to-date subset of the University of Alberta pathogenesis-based
#' transcripts sets (PBTs) that were generated by using Affymetrix Microarrays. Take them just as an illustrative
#' example.
#'
#' @format An object of class "list" of length 5. Each one of its elements is a "character" vector
#' of ENTREZ gene identifiers.
#' @source \url{https://www.ualberta.ca/medicine/institutes-centres-groups/atagc/research/gene-lists.html}
#' @usage data(pbtGeneLists)
"pbtGeneLists"
